95882_Proj/allfootball/allfootball/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

95882_Proj/allfootball/app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('homepage/', views.homepage, name='homepage'),
    path('topics/', views.TopicListView.as_view(), name='topics'),
    path('own_topics/', views.OwnTopicListView.as_view(), name='own_topics'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('redirect_login/', views.to_login, name='redirect_login'),
    path('increase_likes/', views.increase_likes, name='increase_likes'),
    path('increase_favorates/', views.increase_favorates, name='increase_favorates'),
    path('favorate_topics/', views.FavorateListView.as_view(), name='favorate_topics'),
    path('search/', views.SearchListView.as_view(), name='search'),
    re_path(r'(?P<pk>[-\w]+)/$', views.TopicDetailView.as_view(), name='topic_detail'),
]

95882_Proj/allfootball/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <!-- https://fontawesome.com/ -->
  <!-- https://www.google.com/search?hl=xx-elmer&biw=1620&bih=832&tbm=isch&sa=1&ei=E5POWsPRG4Ll_Qanx7HwBg&q=barcelona+camp+non&oq=barcelona+camp+non&gs_l=psy-ab.3...10648.13158.0.13350.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..0.0.0....0.X-MgRg71cDo#imgrc=Ulpr-yUrbhxzlM: -->
    <meta charset="utf-8" />
    <title>All Football</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="/" />
    <script src="https://use.fontawesome.com/3f3d63a639.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static "js/votes.js" %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">All Football</a>
        {% if user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url "app:topics" %}">Hot Topics <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "app:own_topics" %}">Own Topics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "app:favorate_topics" %}">Favorate Topics</a>
              </li>
          </ul>
            <a href="{% url 'app:user_logout' %}"><button class="btn btn-outline-danger my-2 my-sm-0" type="button">Logout</button></a>
          {% else %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url "app:topics" %}">Hot Topics <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url "app:redirect_login" %}">Own Topics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "app:redirect_login" %}">Favorate Topics</a>
                  </li>
              </ul>
            <a href="{% url 'app:user_login' %}"><button class="btn btn-outline-success my-2 my-sm-0" type="button">Login / Register</button></a>
          {% endif %}
        </div>
      </nav>
      <div class="container mycontent">
        {% block content %}
        {% endblock %}
      </div>
</body>
</html>

95882_Proj/allfootball/templates/favorate_topics.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Manage topics of your own:</h1>
        <ul class="list-group">
            {% for topic in topics %}
            <a href="{{ topic.id }}"><li class="list-group-item"><h2>{{ topic.title }}</h2></li></a>
            <em style="text-align:right"><p>By {{ topic.author.username }} at {{ topic.date }}</p></em>
            <div>
                <div style="float:left">
                    <i class="fa fa-tags" aria-hidden="true"></i>
                    {% for tag in topic.tags.all %}
                    {{ tag.label }}
                    {% endfor %}
                </div>
                <div style="float:right">
                    <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                    {{ topic.likes }}
                    <i class="fa fa-heart" aria-hidden="true"></i>
                    {{ topic.favorates }}
                </div>
            </br>
            </br>
            </div>
            {% endfor %}
        </ul>
        <a href="{% url 'app:new_topic' %}"><button type="button" class="btn btn-success">New Topic</button></a>
        <a href="{% url 'app:topics' %}"><button type="button" class="btn btn-warning">Back</button></a>
    </div>
{% endblock %}

95882_Proj/allfootball/templates/homepage.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>All Football</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body background="https://www.airportparkandride.com/wp-content/uploads/2017/08/Camp-Nou-2.jpg" style="background-size:100% 100%">
  <div style="padding-top:25%">
  <a href="{% url "app:user_login" %}"><button type="button" class="btn btn-success btn-lg" style="width:40%; margin-left:30%">Welcome to ALL FOOTBALL</button></a>
  </div>
</body>
</html>

95882_Proj/allfootball/templates/login.html
{% extends "base.html" %}
    {% block content %}
    <div class="jumbotron">
        <h1 class="display-4">ALL HERE IS FOOTBALL!</h1>
        <p class="lead">Please login to begin your discussion.</p>
        <hr class="my-4">
        <form method="post">
          {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="username" class="form-control" id="username" name="username"  placeholder="Username">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Login</button>
            <a href="{% url 'app:register' %}"><button type="button" class="btn btn-warning" onclick="" >Register</button></a>
          </form>
      </div>
    {% endblock %}

95882_Proj/allfootball/templates/login_fail.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Woops! Your password doesn't match your username!!</h1></br></br>
        <a href="{% url "app:user_login" %}"><button type="button" class="btn btn-warning">Go Back</button></a>
    </div>
{% endblock %}

95882_Proj/allfootball/templates/new_topic.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="jumbotron">
        <h1>Post a new Topic:</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form topic_form %}
            <button type="submit" class="btn btn-success">Submit</button>
            <a href="{% url "app:topics" %}"><button type="button" class="btn btn-danger">Cancel</button></a>
        </form>
    </div>
{% endblock %}

95882_Proj/allfootball/templates/own_topics.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Manage topics of your own:</h1>
        <ul class="list-group">
            {% for topic in topics %}
            <a href="{{ topic.id }}"><li class="list-group-item"><h2>{{ topic.title }}</h2></li></a>
            <em style="text-align:right"><p>By {{ topic.author.username }} at {{ topic.date }}</p></em>
            <div style="text-align:right">
                    <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                </div>
            {% endfor %}
        </ul>
        <a href="{% url 'app:new_topic' %}"><button type="button" class="btn btn-success">New Topic</button></a>
        <a href="{% url 'app:topics' %}"><button type="button" class="btn btn-warning">Back</button></a>
    </div>
{% endblock %}

95882_Proj/allfootball/templates/redirect_login.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Please Login to Continue</h1></br>
        <a href="{% url "app:user_login" %}"><button type="button" class="btn btn-success">Go to Login</button></a>

    </div>
{% endblock %}

95882_Proj/allfootball/templates/register.html
{% extends "base.html" %}
{% load bootstrap3 %}
    {% block content %}
    <div class="jumbotron">
        <h1 class="display-4">ALL HERE IS FOOTBALL!</h1>
        {% if registered %}
        <h1>Thank you for registering!</h1></br>
        <a href="{% url "app:topics" %}"><button type="button" class="btn btn-success">Begin your discussion right now!</button></a>
        {% else %}
        <p class="lead">Please fill in following information to register.</p>
        <hr class="my-4">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form userInfo_form %}
            <button type="submit" class="btn btn-success">Submit</button>
            <a href="{% url 'app:user_login' %}"><button type="button" class="btn btn-warning">Switch to Login</button></a>
          </form>
          {% endif %}
    </div>
    {% endblock %}

95882_Proj/allfootball/templates/search_results.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Your Search Results:</h1>
        <i>Based on tags, titles and contents</i></br></br>
        <ul class="list-group">
            {% for topic in topics %}
            <a href="{{ topic.id }}"><li class="list-group-item"><h2>{{ topic.title }}</h2></li></a>
            <em style="text-align:right"><p>By {{ topic.author.username }} at {{ topic.date }}</p></em>
            <div>
                <div style="float:left">
                    <i class="fa fa-tags" aria-hidden="true"></i>
                    {% for tag in topic.tags.all %}
                    {{ tag.label }}
                    {% endfor %}
                </div>
                <div style="float:right">
                    <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                    {{ topic.likes }}
                    <i class="fa fa-heart" aria-hidden="true"></i>
                    {{ topic.favorates }}
                </div>
            </br>
            </br>
            </div>
            {% endfor %}
        </ul>
        <a href="{% url 'app:new_topic' %}"><button type="button" class="btn btn-success">New Topic</button></a>
        <a href="{% url 'app:topics' %}"><button type="button" class="btn btn-warning">Back</button></a>
    </div>
{% endblock %}

95882_Proj/allfootball/templates/topic_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 style="text-align:center">{{ topic.title }}</h1></br>
        <h2 style="text-align:left">{{ topic.content }}</h2>
        <p style="text-align:right"><em>{{ topic.author }} at {{ topic.date }}</em></p>
        <div>
            <div style="float:left">
                    <i class="fa fa-tags" aria-hidden="true"></i>
                    {% for tag in topic.tags.all %}
                    {{ tag.label }}
                    {% endfor %}
            </div>
            <div style="float: right">
                <i class="fa fa-thumbs-o-up" aria-hidden="true" id="likes" topic_id="{{ topic.id }}" onclick="increase_likes()"></i>
                <span id="likes_count">{{ topic.likes }}</span>
                <i class="fa fa-heart" aria-hidden="true" id='favorates' topic_id="{{ topic.id }}" onclick="increase_favorates()"></i>
                <span id="favorates_count">{{ topic.favorates }}</span>
            </div>
        </br>
        </div>
    </br>
        <ul>
            {% for comment in topic.comments.all %}
            <li><p><strong>{{ comment.content }}</strong></p>
                 <p style="text-align:right"><em>By {{ comment.author }} at {{ comment.date }}</em></p>
                </li>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control"  name="comment" placeholder="Leave your comment here..." required/></br>
            <input type="hidden" name="topic_id" value={{ topic.id }} />
            <button type="submit" class="btn btn-success">Comment</button>
            <a href="{% url 'app:topics' %}"><button type="button" class="btn btn-warning">Back</button></a>
        </div>
        </form>
        {% else %}
        <h3>Please Login to Comment</h3></br>
        <a href="{% url "app:user_login" %}"><button type="button" class="btn btn-success">Go to Login</button></a>
        <a href="{% url 'app:topics' %}"><button type="button" class="btn btn-warning">Back</button></a>
        {% endif %}

    </div>
{% endblock %}

95882_Proj/allfootball/templates/topics.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Latest Hot Topics:</h1></br>
        <form method="GET" action="{% url "app:search" %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="search">Search</label>
                <input type="text" class="form-control" id="search" name="content" placeholder="Search..."></br>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>
        <ul class="list-group" id="list">
            {% for topic in topics %}
            <a href="{{ topic.id }}"><li class="list-group-item"><h2>{{ topic.title }}</h2></li></a>
            <em style="text-align:right"><p>By {{ topic.author.username }} at {{ topic.date }}</p></em>
            <div>
                <div style="float: left">
                <i class="fa fa-tags" aria-hidden="true"></i>
                {% for tag in topic.tags.all %}
                {{ tag.label }}
                {% endfor %}
            </div>
                <div style="float: right">
                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                {{ topic.likes }}
                <i class="fa fa-heart" aria-hidden="true"></i>
                {{ topic.favorates }}
                </div>
            </div>
        </br>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
        <a href="{% url 'app:new_topic' %}"><button type="button" class="btn btn-success">New Topic</button></a>
        <a href="{% url 'app:own_topics' %}"><button type="button" class="btn btn-primary">Manage Own Topics</button></a>
        {% else %}
        <a href="{% url 'app:redirect_login' %}"><button type="button" class="btn btn-success">New Topic</button></a>
        <a href="{% url 'app:redirect_login' %}"><button type="button" class="btn btn-primary">Manage Own Topics</button></a>
        {% endif %}
    </div>
{% endblock %}